### 爬取所有股票信息
GET {{host}}/extract/all
Accept: */*

### 推荐股票-最近存在放量的股票，根据成交额排序
POST {{host}}/analysis/recommend
Content-Type: application/json

{
  "store": false,
  "date": "2024-06-28",
  "heavenVolRatio": {
    "days": 6,
    "minVolRatio": 2
  },
  "page": {
    "limit": 1000,
    "orderBy": "amount desc"
  }
}

### 推荐股票-突破形态，最近存在放量
POST {{host}}/analysis/recommend
Content-Type: application/json

{
  "fiveCrossTen": {
    "days": 10
  },
  "heavenVolRatio": {
    "days": 5,
    "minVolRatio": 2
  },
  "minAmount": 200000000,
  "page": {
    "limit": 1000,
    "offset": 0,
    "pageNo": 1,
    "pageSize": 1000
  }
}

### 推荐股票
POST {{host}}/analysis/recommend
Content-Type: application/json

{
  "date": "2021-06-03",
  "fiveAboveTen": {
    "days": 3
  },
  "fiveCrossTen": {
    "days": 5
  },
  "heavenVolRatio": {
    "days": 10,
    "minVolRatio": 2
  },
  "minAmount": 100000000,
  "page": {
    "limit": 1000,
    "offset": 0,
    "pageNo": 1,
    "pageSize": 1000
  }
}

###
POST {{host}}/analysis/score
Content-Type: application/json

{
  "date": "2024-06-30",
  "increaseRatio": {
    "recDays": 3,
    "hisDays": 5,
    "minRatio": 2,
    "minRecInc": 10,
    "maxRecInc": 50
  },
  "turnRatio": {
    "recDays": 3,
    "hisDays": 5,
    "minRatio": 2,
    "minAvgAmount": 1000000000
  },
  "minimumPriceSupport": {
    "recDays": 3
  },
  "amountRatio": {
    "minRatio": 2,
    "recentDays": 3,
    "historyDays": 5
  },
  "heavenVolRatio": {
    "days": 5,
    "minVolRatio": 2
  },
  "fiveCrossTen": {
    "days": 3
  },
  "fiveAboveTen": {
    "days": 3
  },
  "page": {
    "limit": 100,
    "offset": 0
  }
}
###