### 爬取所有股票信息
GET http://localhost:8080/extract/all
Accept: */*

### 推荐股票-最近存在放量的股票，根据成交额排序
POST http://localhost:8080/analysis/recommend
Content-Type: application/json

{
  "store": true,
  "date": "2021-06-01",
  "heavenVolRatio": {
    "days": 6,
    "minVolRatio": 2
  },
  "page": {
    "limit": 1000,
    "orderBy": "amount desc"
  }
}

### 推荐股票-突破形态，最近存在放量
POST http://localhost:8080/analysis/recommend
Content-Type: application/json

{
  "fiveCrossTen": {
    "days": 10
  },
  "heavenVolRatio": {
    "days": 5,
    "minVolRatio": 2
  },
  "minAmount": 200000000,
  "page": {
    "limit": 1000,
    "offset": 0,
    "pageNo": 1,
    "pageSize": 1000
  }
}

### 推荐股票
POST http://localhost:8080/analysis/recommend
Content-Type: application/json

{
  "date": "2021-06-03",
  "fiveAboveTen": {
    "days": 3
  },
  "fiveCrossTen": {
    "days": 5
  },
  "heavenVolRatio": {
    "days": 10,
    "minVolRatio": 2
  },
  "minAmount": 100000000,
  "page": {
    "limit": 1000,
    "offset": 0,
    "pageNo": 1,
    "pageSize": 1000
  }
}

###
