spring:
  application:
    name: finalysis
  datasource:
    url: jdbc:postgresql://localhost:5432/stock
    username: postgres
    password: 191908577
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      # 不用 jpa 删库建表
      ddl-auto: none
    database: POSTGRESQL
    properties:
      hibernate:
        format_sql: true

# mp 打印 sql
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 特定类打印日志
logging:
  level:
    root: info
    xyz.liujin.finalysis.analysis.mapper.DailyAnalysisMapper: debug

##mybatis的相关配置
#mybatis:
#  #mapper配置文件
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: xyz.liujin.finalysis.**.entity
#  #开启驼峰命名
#  configuration:
#    map-underscore-to-camel-case: true